### ISSUE TITLE
dradio kills all mpv instances

### ISSUE THREAD

**Issue by Linux-BA** [mrbooshehri/dradio#1]
I like your script, but like in the title it kills every mpv instances.

So i put the changed lines here, because i don't figure it out how to do it correctly.

First change:
# Functions
play(){
  nohup mpv **--title="dradio"** $1 --stop-playback-on-init-failure --no-video 2&>/dev/null &
  case $2 in

Second change:
  # Stop playing
  "-s"|"--stop")
  	**kill $(ps aux | grep dradio | grep -v grep | awk '{print $2}')** 2&>/dev/null ;;

**Comment by mrbooshehri** [comment]
Thank you for your suggestion, I made the changes.
