### ISSUE TITLE
A small thing - a typo

### ISSUE THREAD

**Issue by plum** [mrbooshehri/dradio#2]
First off, I find your script to be excellent, as something to use, straight for terminal, no tui even. Thank you for sharing it.

In the printout for help, the option dradio ''-d' is annotated as being 'delete' but should be (of course) 'dmenu'

Cheers,
John

**Comment by plum** [comment]
Oh, and concerning the README, I find  happily, that the script plays html urls,  .mp3 and m3u8 in addition to what is stated, I.E.,     .m3u and .pls.

**Comment by mrbooshehri** [comment]
I fixed the problem.
I'm happy you find it useful
